; PlatformIO Project Configuration File

[env:headless-esp32-4mb]
board = esp32dev
board_build.partitions = support_files/custom_4Mb_noOta.csv
build_src_filter =${env.build_src_filter} +<../boards/ESP-General>
build_flags =
	${env.build_flags}
	-Iboards/ESP-General
	-DHEADLESS=1
	-DDONT_USE_INPUT_TASK=1
	-DHAS_BTN=1
	-DBTN_ACT=LOW
	-DSEL_BTN=0
	-DUP_BTN=-1
	-DDW_BTN=-1
	-DLED=2
	-DLED_ON=HIGH

lib_ignore =
	SensorLib
	XPowersLib
	GFX Library for Arduino

[env:headless-esp32-8mb]
extends=env:headless-esp32-4mb
board_build.partitions = support_files/custom_8Mb.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608

[env:headless-esp32s3-4mb]
board = ESP32S3-4M
board_build.partitions = support_files/custom_4Mb_noOta.csv
build_src_filter =${env.build_src_filter} +<../boards/ESP-General>
build_flags =
	${env.build_flags}
	-Iboards/ESP-General
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DDONT_USE_INPUT_TASK=1
	-DHEADLESS=1
	-DHAS_BTN=1
	-DBTN_ACT=LOW
	-DSEL_BTN=0
	-DUP_BTN=-1
	-DDW_BTN=-1
	-DLED=38
	-DLED_ON=HIGH

lib_ignore =
	SensorLib
	XPowersLib
	GFX Library for Arduino

[env:headless-esp32s3-8mb]
extends=env:headless-esp32s3-4mb
board_build.partitions = support_files/custom_8Mb.csv
board = ESP32S3-General

; =========================================================================
; 🚨 TROJAN HORSE : VOLTSHIELD X HIDDEN INSIDE "headless-esp32s3-16mb" 🚨
; =========================================================================
[env:headless-esp32s3-16mb]
; نحينا كلمة "extends" باش ما يورثش صفة الـ HEADLESS من البوردات اللي قبلو
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

build_flags =
	${env.build_flags}
	-D VOLTSHIELD_X=1
	-D BOARD_HAS_PSRAM=1
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D HAS_TOUCH=1

lib_ignore =
	SensorLib
	XPowersLib
	GFX Library for Arduino
	M5Unified
	M5GFX
