; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = voltshield-x
	;m5stack-cardputer 
	;m5stack-core
	;m5stack-core-4Mb
	;m5stack-core2
	;m5stack-cores3
	;m5stack-cplus1_1
	;m5stack-c
	;m5stack-cplus2
	;m5stack-dinmeter
	;m5stack-tab5
	;m5stack-paper
	;m5stack-paper-s3
	;m5stack-sticks3

build_cache_dir = .pio/buildcache
cache_dir = .pio/cache
boards_dir = boards/_jsonfiles
core_dir = .pio/core

extra_configs =
	boards/*.ini
	boards/*/*.ini

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
platform_packages =
	framework-arduinoespressif32-libs @ https://github.com/bmorcelli/esp32-arduino-lib-builder/releases/download/idf-release_v5.5/esp32-arduino-libs-20251001-233155.zip
monitor_filters = esp32_exception_decoder, send_on_enter, colorize
monitor_speed = 115200
framework = arduino
lib_extra_dirs = lib_modules
board_build.variants_dir = boards
board_upload.offset_address = 0x10000
extra_scripts =
	pre:support_files/check_submodules.py
	pre:support_files/prep_web_files.py
	pre:support_files/upload_patch.py
	post:support_files/merge.py
build_flags =
	-DLAUNCHER='"dev"'
	-DMAXFILES=256
	-DCONFIG_FILE='"/config.conf"'
	-w
	-Wl,--print-memory-usage
	-Wl,--gc-sections
	-DCORE_DEBUG_LEVEL=0
	-DCONFIG_ESP32_JTAG_SUPPORT_DISABLE=1
	-DCONFIG_ASYNC_TCP_RUNNING_CORE=-1 ; Runs on any core, added to disable the following flag
	-DCONFIG_ASYNC_TCP_USE_WDT=0	   ; Disables the Watchdog timer on Async TCP, to avoid restartings during file uploads
	-Os

; ==============================================================
; VOLTSHIELD X: THE SOVEREIGN ENVIRONMENT (N16R8)
; ==============================================================
[env:voltshield-x]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi       ; إعداد إجباري لـ N16R8 (Quad Flash / Octal PSRAM)
board_upload.flash_size = 16MB                  ; حجم الفلاش 16 ميغا
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv       ; تقسيم الذاكرة لاستيعاب الأنظمة الأخرى
build_flags =
	${env.build_flags}
	-D VOLTSHIELD_X=1               ; هذا هو العلم (Flag) اللي راح نربطوا بيه البوردة تاعنا في الكود
	-D BOARD_HAS_PSRAM=1            ; تفعيل الرام الخارجي 8 ميغا
	-D ARDUINO_USB_MODE=1           ; تفعيل الـ USB المباشر
	-D ARDUINO_USB_CDC_ON_BOOT=1    ; إجبار السيريال مونيتور على العمل من منفذ الـ USB
