[env:m5stack-cores3]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

build_flags =
	${env.build_flags}
	-D VOLTSHIELD_X=1
	-D BOARD_HAS_PSRAM=1
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D OTA_TAG='"cores3"'
	-D PART_16MB=1
	-D HAS_TOUCH=1

lib_ignore =
	SensorLib
	XPowersLib
	GFX Library for Arduino
	M5Unified
	M5GFX
